strategy:
  matrix:
    node12_linux:
      imageName: 'ubuntu-latest'
      nodeVersion: 12.x
    node12_windows:
      imageName: 'windows-2019'
      nodeVersion: 12.x
    node12_macos:
      imageName: 'macOS-10.14'
      nodeVersion: 12.x
    node10_linux:
      imageName: 'ubuntu-latest'
      nodeVersion: 10.x
    node10_windows:
      imageName: 'windows-2019'
      nodeVersion: 10.x
    node10_macos:
      imageName: 'macOS-10.14'
      nodeVersion: 10.x

pool:
  vmImage: $(imageName)

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
    displayName: 'Install Node.js'

  - script: yarn install --frozen-lockfile
    displayName: 'Install dependencies'

  - script: yarn build
    displayName: 'Build projects'

  - script: yarn lint
    displayName: 'Lint projects'

  - script: yarn test
    displayName: 'Run tests'
